services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: ghcr.io/d1akk/api:latest
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aebbankk
      POSTGRES_DB: aeb-test
      ConnectionStrings__DefaultConnection: "Host=database;Database=aeb-test;Username=postgres;Password=aebbankk"
    depends_on:
      - database

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: ghcr.io/d1akk/client:latest
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - api

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aebbankk
      POSTGRES_DB: aeb-test
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
